### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by trix1210** [sandervdwnl/ajax_product_filters#1]
missing column in table: product_color
table products should be called product

**Comment by sandervdwnl** [comment]
It's there in the sq file, so it should be created.

CREATE TABLE IF NOT EXISTS `products` (
  `product_id` int(11) NOT NULL AUTO_INCREMENT,
  `product_type` varchar(25) NOT NULL,
  `product_brand` varchar(50) NOT NULL,
  `product_color` varchar(25) NOT NULL,
  `product_image` varchar(50) NOT NULL,
  PRIMARY KEY (`product_id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;
